services:
  db:
    image: postgres:15-alpine
    container_name: warehouse_db
    restart: always
    environment:
      POSTGRES_DB: meat_warehouse
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse_user -d meat_warehouse"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: warehouse_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: warehouse_web
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=meat_warehouse
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=warehouse_pass
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    container_name: warehouse_celery
    entrypoint: []
    command: bash -c "sleep 10 && celery -A config worker -l info"
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=meat_warehouse
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=warehouse_pass
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    container_name: warehouse_beat
    entrypoint: []
    command: bash -c "sleep 15 && celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=meat_warehouse
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=warehouse_pass
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
