# Generated by Django 6.0.7 on 2026-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='Номер заявки'),
        ),
    ]
