# # Generated by Django 6.0.7 on 2026-08-17 17:15
#
# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('orders', '0005_add_order_number'),
#     ]
#
#     operations = [
#     ]
from django.db import migrations


def populate(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for i, order in enumerate(Order.objects.order_by('created_at'), start=1):
        order.order_number = i
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0005_add_order_number'),
    ]

    operations = [
        migrations.RunPython(populate, migrations.RunPython.noop),
    ]