# Generated by Django 6.0.7 on 2026-08-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_populate_order_numbers'),
    ]

    operations = [
    ]
